input_features: 3
n_labels: 10
n_units: 64
n_units_att: 16
num_inducing_points: 8
n_heads: 10
n_dense_layers: 2
n_attention_layers: 2
batch_size: 32
lr: 0.002

epochs: 2000
steps_per_epoch: 500
validation_steps: 100
